CREATE TABLE user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nickname VARCHAR(255) NOT NULL,
  mail     VARCHAR(255) NOT NULL,
  password VARCHAR(100) NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE unique_idx_nickname (nickname)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

